import './globals.css'
import { Inter } from 'next/font/google'
import { NoteProvider } from '../../src/app/contexts/noteContext'
import { ThemeProvider } from './contexts/theme/ThemeContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <link rel="manifest" href="manifest.jason"></link>
        <body className={inter.className}>
          <NoteProvider>
            {children}
          </NoteProvider>
        </body>
      </html>
    </ThemeProvider>
  )
}